
```{r}
library(tidyverse)
```


```{r}
#read data.
cover <- read.csv("../Raw data/alledata-cover.csv")

frekvens <- read.csv("../Raw data/alledata-frekvens.csv")

abiotiske <- read.csv("../Raw data/alledata-abiotiske.csv")
artslist <- read.csv("../Raw data/artsliste.csv")
traits <- read.csv("../Raw data/traits.csv")

cover_taxa <- read.csv("../Raw data/alledata-cover-samletaxa.csv") 
frekvens_taxa <- read.csv("../Raw data/alledata-frekvens-samletaxa.csv")

```


Merge the data together, and rename some of the columns to indicate if it is from cover data or frekvens data.
```{r}
frekvens_cover <- merge(frekvens,cover, by = c("plot","site","year"),suffixes = c("Frekvens","Cover"))

frekvens_cover <- setNames(frekvens_cover,paste0(names(frekvens_cover),ifelse(names(frekvens_cover) %in% setdiff(names(frekvens),names(cover)),"frekvens","")))

frekvens_cover <- setNames(frekvens_cover,paste0(names(frekvens_cover),ifelse(names(frekvens_cover) %in% setdiff(names(cover),names(frekvens)),"cover","")))
 
df1 <- merge(abiotiske, frekvens_cover, by = c("plot","site","year"))
df1 <- merge(df1, frekvens_taxa, by = c("plot","site","year"))
df1 <- merge(df1, cover_taxa, by = c("plot","site","year"))

```


Select data from 2014 and enebærkrat (5130). 
```{r}
data_2014_full <- df1[df1$terhabtype == "{5130}" & df1$year == 2014,]
```



Remove all the columns with only 0 values or only mv (missing values).
```{r}
data_2014 <- data_2014_full[, colSums(data_2014_full != 0) > 0]
data_2014 <- data_2014[, colSums(data_2014 != "mv") > 0]
```



```{r}
data_2014$total_obs <- rowSums(data_2014[,grep("Cover", names(data_2014))])
```


```{r}
data_2014$shanon_index <- rowSums(-data_2014[, grep("Cover", names(data_2014))]/data_2014$total_obs * log(data_2014[, grep("Cover", names(data_2014))]/data_2014$total_obs), na.rm = TRUE  )
```

```{r}
write.csv(data_2014, file = "Data/Processed data//data_2014_5130.csv")
```




