
```{r}
library(tidyverse)
```


```{r}
#read data.
cover <- read.csv("../../Raw data/alledata-cover.csv")

frekvens <- read.csv("../../Raw data/alledata-frekvens.csv")

abiotiske <- read.csv("../../Raw data/alledata-abiotiske.csv")
artslist <- read.csv("../../Raw data/artsliste.csv")
traits <- read.csv("../../Raw data/traits.csv")

cover_taxa <- read.csv("../../Raw data/alledata-cover-samletaxa.csv") 
frekvens_taxa <- read.csv("../../Raw data/alledata-frekvens-samletaxa.csv")

```


Merge the data together, and rename some of the columns to indicate if it is from cover data or frekvens data.
```{r}
frekvens_cover <- merge(frekvens,cover, by = c("plot","site","year"),suffixes = c("Frekvens","Cover"))

frekvens_cover <- setNames(frekvens_cover,paste0(names(frekvens_cover),ifelse(names(frekvens_cover) %in% setdiff(names(frekvens),names(cover)),"frekvens","")))

frekvens_cover <- setNames(frekvens_cover,paste0(names(frekvens_cover),ifelse(names(frekvens_cover) %in% setdiff(names(cover),names(frekvens)),"cover","")))
 
df1 <- merge(abiotiske, frekvens_cover, by = c("plot","site","year"))
df1 <- merge(df1, frekvens_taxa, by = c("plot","site","year"))
df1 <- merge(df1, cover_taxa, by = c("plot","site","year"))

```


Select data from 2014 and enebærkrat (5130). 
```{r}
data_2014_full <- df1[df1$terhabtype == "{5130}" & df1$year == 2014,]
```


```{r}
taxa1 <- cover_taxa[cover_taxa$site == c(5203) & cover_taxa$year == 2014,]
```



Remove all the columns with only 0 values or only mv (missing values).
```{r}
data_2014 <- data_2014_full[, colSums(data_2014_full != 0) > 0]
data_2014 <- data_2014[, colSums(data_2014 != "mv") > 0]
```



```{r}
data_5130_full <- df1[df1$terhabtype == "{5130}",]


data_5130 <- data_5130_full[, colSums(data_5130_full != 0) > 0]
data_5130 <- data_5130[, colSums(data_5130 != "mv") > 0]
```

```{r}
write.csv(data_5130, file = "../Data/Processed data//data_5130.csv" , row.names=FALSE)
```

Create a function to create datasets of terhabtype.




```{r}
create_terhab_data <- function(terhabtype, cover =NULL, frekvens = NULL, abiotiske = NULL, artslist = NULL, traits = NULL, cover_taxa = NULL, frekvens_taxa = NULL  ) {
  if (is.null(cover)) {
    cover <- read.csv("../../Raw data/alledata-cover.csv")
  }
  if (is.null(frekvens)) {
    frekvens <- read.csv("../../Raw data/alledata-frekvens.csv")
  }
  if (is.null(abiotiske)) {
    abiotiske<- read.csv("../../Raw data/alledata-abiotiske.csv")
  }
  if (is.null(artslist)) {
    artslist <-  read.csv("../../Raw data/artsliste.csv")
  }
  if (is.null(traits)) {
    traits <- read.csv("../../Raw data/traits.csv")
  }
  if (is.null(cover_taxa)) {
    cover_taxa <- read.csv("../../Raw data/alledata-cover-samletaxa.csv")
  }
  if (is.null(frekvens_taxa)) {
    frekvens_taxa <- read.csv("../../Raw data/alledata-frekvens-samletaxa.csv")
  }
  
  
  #Merge All the data together
  
  frekvens_cover <- merge(frekvens,cover, by = c("plot","site","year"),suffixes = c("Frekvens","Cover"))

  frekvens_cover <- setNames(frekvens_cover,paste0(names(frekvens_cover),ifelse(names(frekvens_cover) %in% setdiff(names(frekvens),names(cover)),"frekvens","")))

frekvens_cover <- setNames(frekvens_cover,paste0(names(frekvens_cover),ifelse(names(frekvens_cover) %in% setdiff(names(cover),names(frekvens)),"cover","")))
 
df1 <- merge(abiotiske, frekvens_cover, by = c("plot","site","year"))
df1 <- merge(df1, frekvens_taxa, by = c("plot","site","year"))
df1 <- merge(df1, cover_taxa, by = c("plot","site","year"))


#change terhabtype input to string and the correct format

terhabtype <- paste0("{",toString(terhabtype),"}")

# select the choosen terhabtype
df2 <- df1[df1$terhabtype == terhabtype ,]

# remove species that were not observed or variables with only missing value
df2 <- df2[, colSums(df2 != 0) > 0]
df2 <- df2[, colSums(df2 != "mv") > 0]

return(df2)
}
```

```{r}
data_6230 <-  create_terhab_data(6230)
```

```{r}
write.csv(data_6230, file = "../Data/Processed data//data_6230.csv" , row.names=FALSE)
```

Surgræsland (6230)

```{r}
data_6230_cover <- cover[abiotiske$terhabtype == "{6230}",]
data_6230_frekvens <- frekvens[abiotiske$terhabtype == "{6230}",]
```



```{r}
write.csv(data_6230_cover, file = "../Data/Processed data//data_6230_cover.csv",  row.names=FALSE)
write.csv(data_6230_frekvens, file = "../Data/Processed data//data_6230_frekvens.csv" , row.names=FALSE)
```

