
```{r}
library(tidyverse)
library(ggmap)
library(tmaptools)
library(sp)
library(rgdal)
library(mapproj)
library(ggrepel)
library(osmar)
library(maps)
library(OpenStreetMap)
library(gganimate)
library(ggplot2)
library(gifski)
library(png)
```
Load the function
```{r}
source("functions.r")
```

Load the data
```{r}
data_5130 <-read.csv("../Data/Processed data/data_5130.csv")
```


Get the long lat values for each plot
```{r}
data_5130 <- convert_to_longlat(data_5130, data_5130$UTMx, data_5130$UTMy)
```




```{r}
world.map <- map_data ("world")
map1 <- world.map %>% filter(region == "Denmark")
```


```{r}
ggplot(map1)+ 
  geom_map(map = map1, aes(long, lat, map_id = region), fill="white", colour = "black") + 
  coord_map() + 
  geom_point(data = data_5130, aes(y=latitude, x = longtitude, colour = factor(year)), alpha = .9, size =2) +
  geom_text_repel(data  = data_5130, aes(y=latitude, x = longtitude, label=site),hjust=0, vjust=0, max.overlaps = 100)
```


Get mean postion for each site

```{r}
mean_site_pos <-  data_5130 %>%
                group_by(site) %>% 
                  summarise_at(vars(longtitude, latitude),mean,na.rm = TRUE)
  
  
mean_site_pos <-  rename(mean_site_pos, longtitude_mean_site = longtitude, latitude_mean_site = latitude)

data_5130 <-left_join(data_5130,mean_site_pos, by = "site")
```


plot each site
```{r}
ggplot(map1)+ 
  geom_map(map = map1, aes(long, lat, map_id = region), fill="white", colour = "black") + 
  coord_map() + 
  geom_point(data = data_5130, aes(y=latitude, x = longtitude, colour = factor(year)), alpha = .9, size =2) +
  geom_text_repel(data  = mean_site_pos, aes(y=latitude_mean_site, x = longtitude_mean_site, label=site),hjust=0, vjust=0)
```

Save the changes
```{r}
write.csv(data_5130, file = "../Data/Processed data//data_5130.csv", row.names=FALSE)
```



```{r}
animation_map <- function(data_frame_in, longtitude, latitude, index, time, duration_time = 15) {
  library(ggplot2)
  library(gifski)
  library(png)
  index <- deparse(substitute(index))
  time <- deparse(substitute(time))
  latitude <- deparse(substitute(latitude))
  longtitude <- deparse(substitute(longtitude))
  
  map_ani <-  ggplot(map1)+ 
  geom_map(map = map1, aes(long, lat, map_id = region), fill="white", colour = "black") +
  coord_map()

map_ani <-  map_ani +
  geom_point(data = data_frame_in, aes(y= .data[[latitude]], x = .data[[longtitude]], colour = .data[[index]]), alpha = .9, size =5) + 

  scale_color_gradientn(colours = rainbow(5)) +
  transition_states(factor(data_frame_in[[time]]), transition_length = 1, state_length = 1) +
  labs(title = "Year: {next_state}")

animate(map_ani,  nframes = 2*length(unique(data_frame_in[[time]])), duration = duration_time)

}
```


```{r}
animation_map(data_5130, longtitude, latitude, simple_shanon_index, year )
```



```{r} 

```


Open street map

```{r}
map_bing <- openmap(c(53.38332836757155,-130.517578125),c(15.792253570362446,-67.939453125),4,'bing')
plot.OpenStreetMap(map_bing)
```


```{r}
map_data <-  data_5130[data_5130$site == 4531,] %>%  select(longtitude, latitude, longtitude_mean_site, latitude_mean_site)
```


```{r}
x_min <- min(map_data$longtitude)
x_max <- max(map_data$longtitude)
y_min <-  min(map_data$latitude)
y_max <- max(map_data$latitude)

x_min_proj <-  x_min - (x_max - x_min) *0.2
x_max_proj <-  x_max + (x_max - x_min) *0.2

y_min_proj <-  y_min - (y_max - y_min) *0.2
y_max_proj <-  y_max + (y_max - y_min) *0.2

lat_mean <-  map_data$latitude_mean_site[1]
long_mean <- map_data$longtitude_mean_site[1]

max_diff <- (max((x_max - x_min), (y_max - y_min)))/2

x_min_proj2 <- min(x_min - (x_max - x_min) *0.2, long_mean- max_diff)
x_max_proj2 <- max(x_max + (x_max - x_min) *0.2, long_mean + max_diff)

y_min_proj2 <- min(y_min - (y_max - y_min) *0.2, lat_mean- max_diff)
y_max_proj2 <-  max(y_max + (y_max - y_min) *0.2, lat_mean + max_diff)

map_test <- openmap(c(y_max_proj2,x_min_proj2),c(y_min_proj2,x_max_proj2),zoom = NULL,'bing')
```

```{r}
map_test2 <- openproj(map_test, projection = "+proj=longlat")
```


```{r}
OpenStreetMap::autoplot.OpenStreetMap(map_test2) + geom_point(data = map_data, mapping = aes(x = longtitude, y = latitude), color = "red", size = 4)
```

```{r}
map_test <- openmap(c(y_max,x_min),c(y_min,x_max),zoom = NULL,'bing')
OpenStreetMap::autoplot.OpenStreetMap(map_test)
```

