
```{r}
library(tidyverse)
```


```{r}
data_2014 <- read.csv("../Data/Processed data/data_2014_5130.csv")
data_5130 <- read.csv("../Data/Processed data/data_5130.csv")
```


```{r}
ggplot(data = data_2014, mapping = aes(x = antalarter, y = shanon_index, group = site)) + 
  geom_point(mapping = aes( color = factor(site)), size = 4)
```

```{r}
ggplot(mapping =  aes( x = data_5130[,grep("X7180Cover", names(data_5130))]/16)) + 
  geom_histogram()
```


```{r}
ggplot(data = data_5130, mapping = aes(x = factor(year), y = simple_shanon_index)) + 
  geom_boxplot() + geom_jitter(width=0.1,alpha=0.2)
```


Ser om der er forskel plots med enebær og ikke enebærbuske.

```{r}
ggplot(data = data_5130, mapping = aes(x = factor(year), y = simple_shanon_index, fill = factor(enebær))) + 
  geom_boxplot() + geom_jitter(width=0.1,alpha=0.2)
```

Vi har meget få obervation hvor der ikke er enebær busk til stede.



```{r}
ggplot(data = data_5130, mapping = aes(x = as.numeric(enebær5md), y = simple_shanon_index)) + 
  geom_point() + 
  geom_smooth(method = "lm", formula =  y~x)
```
  

```{r}
lm(data_5130$simple_shanon_index ~ as.numeric(data_5130$enebær5md ))
```



```{r}
ggplot(data = data_5130, mapping = aes(x = , y = shanon_index_v2)) + 
  geom_point()
```



Diversitets plots, different indexes.


```{r}
ggplot(data = data_5130, mapping = aes(y =shanon_index_v2_mme , x = simple_shanon_index)) +
  geom_point(aes(color = factor(year)), size = 2) + 
  geom_abline()
```

A boxplot comparing the difference between the simple shanon index and shanon index v1

```{r}
ggplot(data = data_5130, mapping = aes(x = factor(year), y = (shanon_index_v1 - simple_shanon_index)))+ 
  geom_boxplot()
```

